/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

import kata.base.Score.CHANCE

class Yahtzee {
    companion object {
        fun score(score: Score, dice1: Int, dice2: Int, dice3: Int, dice4: Int, dice5: Int): Int {
            val dices = listOf(dice1, dice2, dice3, dice4, dice5)

            return if (score == CHANCE) chance(dices)
            else yahtzee(dices)
        }

        private fun yahtzee(dices: List<Int>) =
            if (dices.toSet().size == 1) 50
            else 0

        private fun chance(dices: List<Int>) = dices.sum()
    }
}


fun main() = print("Hello, Yahtzee!")
