/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

class Yahtzee {
    companion object {
        fun score(
            category: Category,
            dice1: Int,
            dice2: Int,
            dice3: Int,
            dice4: Int,
            dice5: Int
        ): Int {
            val dices = listOf(dice1, dice2, dice3, dice4, dice5)

            return category.calculateScore(dices)
        }
    }
}


fun main() = print("Hello, Yahtzee!")
